MinecraftHopper/MinecraftHopper

- _help/dxdiag/index.markdown
> Made design of dxdiag page nicer.

- _help/out-of-memory/index.markdown
> Fixed link in 'out of memory' article

- _help/setting-up-java-server/index.markdown
Adds info on the server console and MacOS, and improves the page layout. #63
> Improve page on setting up servers

- _help/archive/resetting-your-minecraft-options/index.html
- _help/failed-to-load-player-skull/index.markdown
- _help/guides/installing-java/index.html
- _help/guides/reinstalling-java/index.html
- _help/guides/reinstalling-minecraft/index.html
- _help/kb/org-lwjgl-pixel-format-05/index.html
- _help/out-of-bounds/index.html
- _help/references/intel-4-series-chipsets/index.html
- _help/reinstalling-minecraft/index.markdown
> Redirects and reinstalling minecraft (#74)

- _help/guides/changing-java-version/index.markdown
- _help/guides/running-sfc-scan/index.markdown
Ported 2 articles from old Hopper
> Port fixes

- _help/hjt/index.markdown
Replace all instances of HJT with HijackThis.
> Replace HJT with HijackThis

- _help/removing-malware/index.markdown
Fix spelling mistakes and improve clarity
> Fix removing malware article

- _help/guides/changing-java-version/index.markdown
This may have fixed the error, however will need to be double checked
> Fixed installing java article 404 error

- _help/guides/changing-java-version/index.markdown
this seems like a minor oversight
> Fix missing file extention

- _help/setting-up-java-server/index.markdown
Remove `@echo off` and add a much-needed line break
> Fix Windows commands

- _help/dxdiag/index.markdown
tells people if someone is helping them, give that person url
> send back to person who asked

- _help/dxdiag/index.markdown
Reverts MinecraftHopper/MinecraftHopper#101
> Revert "send back to person who asked"

- _help/guides/xbox-privacy/index.markdown
Links and URLs were missing from rendered HTML page.
> Updated markdown link tags

- _help/guides/installing-mods/fabric/index.markdown
Several hopper links on the page were incorrect, leading to a 404 page
> Correct links

- _help/guides/xbox-privacy/index.markdown
in #115 i missed two others of the same link, i've fixed this
> Missed a few links in xbox-privacy

- _help/exit-code/code-805306369/index.markdown
Malwarebytes article no longer exists and I believe this is the closest article to that one, telling users how to run a scan.
> Replace broken link

- _help/known-incompatible-software/index.html
This is only moving two sentences around so it makes more sense. I also added the option for the user to uninstall it.
> Slight revision

- _help/known-incompatible-software/index.html
Adding more symptoms of Killer Intelligence Center to the list, as well as renaming to its proper program name. I did not change the "last edited" time, but this should be the last time that I propose changes regarding Killer.
> Update index.html - last time

- factoids.json
paste.ubuntu.com now requires account creation to upload a paste.
> Change paste sites to paste.gg

- _help/nvidia-optimus/index.md
Includes the MS store launcher path and updated legacy launcher path
> Update optimus steps

- _help/installing-java/index.markdown
This pull request adds information about Java 21 to https://minecrafthopper.net/help/installing-java/.
> Java 21 (Fix #79)
